# Load default config + the dl plugin
imports:
  - { resource: "EXT:rte_ckeditor/Configuration/RTE/Default.yaml" }
  - { resource: "EXT:rte_ckeditor_dl/Configuration/RTE/Plugin.yaml" }

# Add dl button to toolbar
editor:
  config:
    toolbar:
      items:
        - definitionList
